# Generated by Django 4.2.9 on 2024-08-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=50)),
                ('about_description', models.CharField(max_length=50)),
                ('about_image', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('linkedin', models.CharField(max_length=20)),
                ('instagram', models.CharField(max_length=20)),
                ('git', models.CharField(max_length=20)),
            ],
        ),
    ]
