# Generated by Django 4.2.9 on 2024-08-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_blog', models.CharField(max_length=50)),
                ('title_blog', models.CharField(max_length=50)),
                ('description_blog', models.CharField(max_length=50)),
                ('isBlog_blog', models.BooleanField()),
            ],
        ),
    ]
