# Generated by Django 4.2.9 on 2024-08-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('konum', models.CharField(max_length=50)),
                ('konum2', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=11)),
                ('mail', models.CharField(max_length=20)),
            ],
        ),
    ]
