# Generated by Django 4.2.9 on 2024-08-31 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_portfoy_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categori', models.CharField(max_length=15)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.blog_kategori'),
        ),
    ]
