# Generated by Django 4.2.9 on 2024-08-31 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog_kategori_blog_blog_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.portfoy_kategori'),
        ),
        migrations.DeleteModel(
            name='blog_kategori',
        ),
    ]
