# Generated by Django 4.2.9 on 2024-08-31 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blog_blog_kategori_delete_blog_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_kategori',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.portfoy_kategori'),
        ),
    ]
