# Generated by Django 4.2.9 on 2024-09-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_blog_blog_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='img_blog',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
