# Generated by Django 4.2.9 on 2024-09-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_uploadmodel_alter_blog_img_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_blog',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
