# Generated by Django 4.2.9 on 2024-09-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_blog_img_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img_blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
