# Generated by Django 4.2.9 on 2024-09-04 22:39

# from django_ckeditor_5.fields import CKEditor5Field
from ckeditor.fields import RichTextField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_blog_img_blog_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfoy_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('description', RichTextField()),  # ✅ Doğru
                ('images', models.ImageField(upload_to='')),
                ('isActive', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('portfoyKategori', models.ManyToManyField(to='home.portfoy_kategori')),
            ],
        ),
    ]
