# Generated by Django 4.2.9 on 2024-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_portfoy_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoy_project',
            name='portfoyKategori',
            field=models.ManyToManyField(default='', to='home.portfoy_kategori'),
        ),
    ]
