# Generated by Django 4.2.9 on 2024-09-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_portfoy_project_portfoykategori_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='portfoy_project',
            name='categories',
        ),
        migrations.AlterField(
            model_name='portfoy_project',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blog_kategori'),
        ),
        migrations.AddField(
            model_name='portfoy_project',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.portfoy_kategori'),
            preserve_default=False,
        ),
    ]
