# Generated by Django 4.2.9 on 2024-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AlterField(
            model_name='blog_kategori',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
