# Generated by Django 4.2.9 on 2024-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_blog_kategori_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
