# Generated by Django 4.2.9 on 2024-09-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_title_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_controller_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu_ismi', models.CharField(max_length=20)),
                ('link', models.SlugField(blank=True, unique=True)),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
