# Generated by Django 4.2.9 on 2024-09-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_admin_controller_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_controller_link',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
