# Generated by Django 4.2.9 on 2024-09-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_delete_admin_controller_link_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description_blog',
            field=models.TextField(),
        ),
    ]
