# Generated by Django 4.2.9 on 2024-09-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_blog_description_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
