# Generated by Django 5.1.6 on 2025-03-13 11:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_about_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
